spring.application.name=gestaoLabBack

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/gestaolab_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.datatype.datetime.write-dates-as-timestamps=false

api.security.token.secret=${JWT_SECRET}
api.security.token.expiration-ms=86400000
api.security.session.inactivity-timeout-ms=1800000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads/arquivos
app.upload.dir.usuarios=uploads/usuarios

spring.web.resources.static-locations=file:uploads/,classpath:/static/

app.fuso-horario=America/Cuiaba
app.reserva.duracao-minima-minutos=15
app.reserva.duracao-maxima-horas=12
app.reserva.antecedencia-maxima-dias=60
